### PR TITLE
Implement upstream API changes

### PR DESCRIPTION
**Pull request by jtagcat**

### CODE REVIEW

**Review by cehbz — CHANGES_REQUESTED** [review]
Looks good except for the commented out code in GroupStruct.Tags(). No need to comment it out just delete it and I'll merge unless there's some reason for it?

**Review by cehbz — COMMENTED** [review]
Could have a custom json bool serializer/deserializer, or just leave as a string and make the client deal with it. I don't care either way.

BTW the API maintainers have been receptive to fixing things like this in the past if you want to point it out to them.

**Comment by jtagcat** [comment]
> commented code at GroupStruct.Tags

Right, removed; thought the json parser did know to convert string to int. Rebase-edited and force-pushed to avoid unneeded commits.

Though, with the bools, I left them at strings. I don't know how you'd call a function within a type/struct (please run this, and use the return instead). Calling a function within a struct is probably not the way to do it, yet I can't think of a better way.  
Mind this, I'm not very good at golang, or probably anything.

> Could have a custom json bool serializer/deserializer, or just leave as a string and make the client deal with it. I don't care either way.

Oh neet, how do you implement it within the nested already existing structs? Are you supposed to wrap the deserialized in a function 'if you encounter string "0", and struct says bool, convert it to false'? Still, doing it json-global sounds not sustainable for potential future™ (in other projects). What if tags:[] uses 0→false, 1→true; categories:[] uses 1→false... ..and I feel it would be better not to deserialize in multiple parts.

**Review by cehbz — APPROVED** [review]

**Review by cehbz — APPROVED** [review]

**Review by cehbz — APPROVED** [review]

**Comment by jtagcat** [comment]
(pls tag a release)

**Pull request merged**
